# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    release/release:
      - step:
          name: Deploy to release demo
          deployment: test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to release demo environment"
            - pipe: atlassian/sftp-deploy:0.5.5
              variables:
                USER: '${SERVER_USER}'
                SERVER: '${SERVER_IP}'
                REMOTE_PATH: '${DEMO_WS}/printcalendar'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/*' # Optional.
                DEBUG: 'true' # Optional.

